#!/bin/bash
echo "FATAL SECURITY WARNING!"
echo "Please note. Certificate verification has been disabled in this copy of Firefox."
echo "This means that anyone can hijack your web-browsing traffic while using this browser."
echo "You will have no garuntee of confidentiality, security, or privacy while using this application."
echo "We have attempted to insure that code from this browser will not leak into any other browsers on your machine, but we can not absolutely insure this."
echo "Please press enter to continue using this application, or press control-c to exit."
read
if [ -e "`pwd`/ff/firefox/firefox" ]
then
echo "Using local copy of firefox at \"`pwd`/ff/firefox/firefox\""
ff="`pwd`/ff/firefox/firefox"
ffcode="0"
else
ff="$(which firefox)"
ffcode=$?
if [ "$ffcode" == "0" ]
then
echo "Probably using a system copy of firefox at \"${ff}\""
fi
fi
if [ "$ffcode" == "0" ]
then
cd extension
xvfb-run -w 0 cfx -b "${ff}" run >../firefox.log 2>&1 &
pid=$!
echo "running xvfb and firefox with pid ${pid}"
else
echo "The firefox binary could not be located. Please install Firefox from your systems package repositories."
fi

