# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1373168666);
user_pref("app.update.lastUpdateTime.background-update-timer", 1373261685);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1373168786);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1373253699);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1373261565);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.migration.version", 10);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 4791);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1373253714981");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1373253718793");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1373340118793");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1366942651552");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1366942959066");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1366861212354");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 5995);
user_pref("datareporting.sessions.current.main", 1307);
user_pref("datareporting.sessions.current.sessionRestored", 6097);
user_pref("datareporting.sessions.current.startTime", "1373290610141");
user_pref("datareporting.sessions.current.totalTime", 8);
user_pref("datareporting.sessions.currentIndex", 29);
user_pref("datareporting.sessions.previous.26", "{\"s\":1373168302581,\"a\":0,\"t\":8,\"c\":false,\"m\":1378,\"fp\":5934,\"sr\":6028}");
user_pref("datareporting.sessions.previous.27", "{\"s\":1373261440532,\"a\":0,\"t\":9,\"c\":false,\"m\":1643,\"fp\":6821,\"sr\":6926}");
user_pref("datareporting.sessions.previous.28", "{\"s\":1373262404607,\"a\":0,\"t\":5,\"c\":false,\"m\":19,\"fp\":1214,\"sr\":1270}");
user_pref("datareporting.sessions.prunedIndex", 25);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 13);
user_pref("extensions.blocklist.pingCountVersion", 8);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/home/bmmcginty/programming/clifox/ff/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1371560990000,\"rdfTime\":1371560042000}}}]");
user_pref("extensions.lastAppVersion", "22.0");
user_pref("extensions.lastPlatformVersion", "22.0");
user_pref("extensions.newAddons", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gecko.buildID", "20130618035212");
user_pref("gecko.mstone", "22.0");
user_pref("idle.lastDailyNotification", 1373253757);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("permissions.default.image", 2);
user_pref("places.database.lastMaintenance", 1373253716);
user_pref("places.history.expiration.transient_current_max_pages", 26029);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1372657422);
user_pref("toolkit.startup.last_success", 1373290611);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("toolkit.telemetry.previousBuildID", "20130618035212");
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1374937347);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
