# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1366861941);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1366861213);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1366861332);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1366947612354");
user_pref("datareporting.policy.firstRunTime", "1366861212354");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 1257);
user_pref("datareporting.sessions.current.main", 31);
user_pref("datareporting.sessions.current.sessionRestored", 1305);
user_pref("datareporting.sessions.current.startTime", "1366866112128");
user_pref("datareporting.sessions.current.totalTime", 5453);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1366861209672,\"a\":0,\"t\":8267,\"c\":false,\"m\":1144,\"fp\":4500,\"sr\":4694}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1366861818276,\"a\":0,\"t\":8094,\"c\":false,\"m\":1209,\"fp\":4467,\"sr\":4636}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1366862949418,\"a\":0,\"t\":5511,\"c\":false,\"m\":22,\"fp\":1326,\"sr\":1412}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1366864811594,\"a\":0,\"t\":5431,\"c\":false,\"m\":22,\"fp\":1251,\"sr\":1335}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1366865260560,\"a\":0,\"t\":5512,\"c\":false,\"m\":24,\"fp\":1312,\"sr\":1360}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1366865869842,\"a\":0,\"t\":5534,\"c\":false,\"m\":21,\"fp\":1336,\"sr\":1385}");
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/home/bmmcginty/projects/ffinstall/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1365737673000}}},{\"name\":\"app-profile\",\"addons\":{\"mozrepl@hyperstruct.net\":{\"descriptor\":\"/home/bmmcginty/.mozilla/dev/mozrepl\",\"mtime\":1366837151000}}}]");
user_pref("extensions.lastAppVersion", "20.0");
user_pref("extensions.lastPlatformVersion", "20.0");
user_pref("extensions.newAddons", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gecko.buildID", "20130326150557");
user_pref("gecko.mstone", "20.0");
user_pref("idle.lastDailyNotification", 1366861393);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("permissions.default.image", 2);
user_pref("places.history.expiration.transient_current_max_pages", 26029);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1366866112);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1369453824);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
