# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1367293013);
user_pref("app.update.lastUpdateTime.background-update-timer", 1367279098);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1367293133);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1367293253);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1367278978);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("datareporting.healthreport.currentDaySubmissionFailureCount", 0);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1367286468858");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1367373492155");
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1366942651552");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1366942959066");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1366861212354");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.firstPaint", 3249);
user_pref("datareporting.sessions.current.main", 80);
user_pref("datareporting.sessions.current.sessionRestored", 3337);
user_pref("datareporting.sessions.current.startTime", "1367292891430");
user_pref("datareporting.sessions.current.totalTime", 197735);
user_pref("datareporting.sessions.currentIndex", 16);
user_pref("datareporting.sessions.previous.0", "{\"s\":1366861209672,\"a\":0,\"t\":8267,\"c\":false,\"m\":1144,\"fp\":4500,\"sr\":4694}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1366861818276,\"a\":0,\"t\":8094,\"c\":false,\"m\":1209,\"fp\":4467,\"sr\":4636}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1367160636199,\"a\":0,\"t\":7886,\"c\":false,\"m\":1229,\"fp\":3952,\"sr\":4004}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1367274939889,\"a\":0,\"t\":9462,\"c\":false,\"m\":1197,\"fp\":6011,\"sr\":6089}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1367275146619,\"a\":0,\"t\":8130,\"c\":false,\"m\":1266,\"fp\":4245,\"sr\":4293}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1367278733287,\"a\":0,\"t\":13673,\"c\":false,\"m\":1478,\"fp\":6606,\"sr\":6676}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1367289960425,\"a\":0,\"t\":9046,\"c\":false,\"m\":1251,\"fp\":5074,\"sr\":5123}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1367291370863,\"a\":0,\"t\":5441,\"c\":false,\"m\":17,\"fp\":1257,\"sr\":1305}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1366862949418,\"a\":0,\"t\":5511,\"c\":false,\"m\":22,\"fp\":1326,\"sr\":1412}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1366864811594,\"a\":0,\"t\":5431,\"c\":false,\"m\":22,\"fp\":1251,\"sr\":1335}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1366865260560,\"a\":0,\"t\":5512,\"c\":false,\"m\":24,\"fp\":1312,\"sr\":1360}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1366865869842,\"a\":0,\"t\":5534,\"c\":false,\"m\":21,\"fp\":1336,\"sr\":1385}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1366866112128,\"a\":0,\"t\":5453,\"c\":false,\"m\":31,\"fp\":1257,\"sr\":1305}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1366942583660,\"a\":0,\"t\":9766,\"c\":false,\"m\":1411,\"fp\":6314,\"sr\":6362}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1367084160931,\"a\":0,\"t\":71452885,\"c\":true,\"m\":1320,\"fp\":7528,\"sr\":7645}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1367155665070,\"a\":0,\"t\":9318,\"c\":false,\"m\":966,\"fp\":6689,\"sr\":6817}");
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/home/bmmcginty/projects/ffinstall/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1365737673000}}},{\"name\":\"app-profile\",\"addons\":{\"mozrepl@hyperstruct.net\":{\"descriptor\":\"/home/bmmcginty/.mozilla/dev/mozrepl\",\"mtime\":1366837151000}}}]");
user_pref("extensions.lastAppVersion", "20.0");
user_pref("extensions.lastPlatformVersion", "20.0");
user_pref("extensions.newAddons", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gecko.buildID", "20130326150557");
user_pref("gecko.mstone", "20.0");
user_pref("gfx.blacklist.direct2d", 4);
user_pref("gfx.blacklist.layers.direct3d10", 4);
user_pref("gfx.blacklist.layers.direct3d10-1", 4);
user_pref("gfx.blacklist.layers.direct3d9", 4);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.stagefright", 4);
user_pref("gfx.blacklist.webgl.angle", 4);
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("gfx.blacklist.webgl.opengl", 4);
user_pref("idle.lastDailyNotification", 1367293394);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("permissions.default.image", 2);
user_pref("places.database.lastMaintenance", 1366947794);
user_pref("places.history.expiration.transient_current_max_pages", 26029);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1366947794);
user_pref("toolkit.startup.last_success", 1367292891);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1369453824);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
