user_pref("dom.max_chrome_script_run_time",30);
user_pref("dom.max_script_run_time",30);
user_pref("browser.download.panel.firstSessionCompleted",  true);
user_pref("browser.feeds.showFirstRunUI",  false);
user_pref("browser.link.open_newwindow",3);
user_pref("browser.link.open_newwindow.restriction",  0);
user_pref("browser.rights.3.shown",  true);
user_pref("browser.sessionstore.enabled",  false);
user_pref("browser.sessionstore.max_tabs_undo",  0);
user_pref("browser.sessionstore.max_windows_undo",  0);
user_pref("browser.sessionstore.resume_from_crash",  false);
user_pref("browser.shell.checkDefaultBrowser",  false);
user_pref("browser.startup.homepage_override.mstone",  "ignore");
user_pref("extensions.newAddons",  false);
user_pref("extensions.pendingOperations",  false);
user_pref("extensions.shownSelectionUI",  true);
user_pref("extensions.update.notifyUser",  false);
user_pref("network.cookie.prefsMigrated",  true);
user_pref("plugin.disable_full_page_plugin_for_types",  "application/pdf");
user_pref("plugin.importedState",  true);
user_pref("toolkit.telemetry.prompted",  2);
